#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Capture the list of currently staged files.
STAGED_FILES=$(git diff --cached --name-only)

# Run your formatting command.
npm run format

# Run linting with auto-fix
npm run lint:fix

# Re-add only the originally staged files.
if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi

# Only run commitlint if we're in a git repository and there's a commit in progress
if [ -f .git/COMMIT_EDITMSG ]; then
  npx --no -- commitlint --edit $1
fi
